#server:
#  port:8081
#spring:
#  datasource:
#    driver-class-name: com.mysql.jdbc.Driver
#    url: jdbc:mysql://localhost:3306/cloudm?useUnicode=true&characterEncoding=utf8
#    username: root
#    password: root
#mybatis:
#    mapper-locations: classpath:mapper/**/*.xml
mybatis:
  mapper-locations: classpath*:mapper/**/*.xml
mybatis-plus:
  mapper-locations: classpath*:mapper/**/*.xml